### ISSUE TITLE
ValueError: This solver needs samples of at least 2 classes in the data, but the data contains only one class: 0

### ISSUE THREAD

**Issue by mclpcc** [bartongroup/2passtools#9]
Hi,

I'm testing 2passtools on nanopore cDNA data and I can't understand how to solve this error.

To test 2passtools i basecalled Nanopore Fast5 files, then I re-orient reads to infer strandness using Pychopper and aligned them using minimap2 with the following command line: 

```
minimap2 -a -u f --cs=long --junc-bed ${junc_bedfile} ${index} ${input} > ${outdir}/BC0828_Naive_CHR.sam
```

junc bed file was generated as suggested in minimap2 manual: 

```
paftools.js gff2bed ${GTF} > path/to/annotated_junc.bed
```

Subsequently I started to test 2passtools score on just one sample using the following parameters:

```
2passtools score -f hg38.fa -a annotated_junc.bed -m 'GTAG' -j 4 -c random_forest --keep-all-annot --stranded -o BC0828_Naive_CHR2pass.bed BC0828_Naive_CHR.bam
```

And I run into this error: 

```
"ValueError: This solver needs samples of at least 2 classes in the data, but the data contains only one class: 0". 
```

Attached you can find the complete standard out & err file related to the error.
Thanks in advance
[2passtools_error.txt](https://github.com/bartongroup/2passtools/files/8700242/2passtools_error.txt)
.

**Comment by mparker2** [comment]
Hi @mclpcc,

in the annotation-aided mode you are using, 2passtools uses the junctions from the bam file that are supported by the junctions in your annotated_junc.bed bed file as positive examples to train a random forest classifier (ExtraTreesClassifier from scikit-learn). I think the error you are getting (which is not handled very well, sorry) is because there are no junctions in the bam file that are supported by the gtf/bed annotation file, hence all the examples in the training data are negative. This causes an error from scikit-learn because ExtraTreesClassifier needs both positive and negative examples.

It seems unlikely that there is really no overlap between the junctions from your bam file and the gtf file. What seems more likely to me is a different naming convention for chromosomes/contigs, e.g. chr1 in the bam file might be 1 or Chr1 in the gtf file. Can you check to see whether that is the case?

I can also make some changes to 2passtools to make sure this error is handled better in future versions.

**Comment by mparker2** [comment]
actually looking at your complete stdout it seems that the error is coming from the input to the logistic regression model rather than the random forest. I think that the cause (no overlap between bam and bed junctions) might still be the same, however.

**Comment by mclpcc** [comment]
Hi!
probably I got your point, maybe the problem could be that I'm using a GENCODE reference GTF file converted in bed12 format. Is it the right input? If not, what should I use?

**Comment by mparker2** [comment]
is your fasta file which you aligned the nanopore reads to also from GENCODE?

**Comment by mclpcc** [comment]
yes, I used the same naming convention between fasta, bed and bam. In any case, what type of .bed did you use for 2passtools paper? And for junction bed do you mean the introns coordinates or exons coordinates?

**Comment by mparker2** [comment]
hmm ok. The bed file that you pass with the `-a` flag should contain intron coordinates. The output from `paftools gff2bed` should be fine though. Please can you try running again but with the flag `-v DEBUG` and send the stderr?

**Comment by mparker2** [comment]
that should print out a confusion matrix which should hopefully tell us whether the issue is with the annotation, or whether something is going wrong with the first step of classification

**Comment by mparker2** [comment]
Oh! sorry, yes bed12 is not right. You should use the `-j` flag with `paftools.js gff2bed` to get a 5-column bed file of intron coordinates rather than a 12-column file of full gene models. I think that is the problem.

**Comment by mclpcc** [comment]
It worked perfectly!

thank you very much for your reaidness and availability!

**Comment by mparker2** [comment]
no worries 😀
